apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
  init.sh: |
    #!/bin/sh

    # create the authentication key
    set -euo pipefail
    apk add openssl
    openssl rand -hex 32 | tr -d "\n" > /root/jwt.hex

  probe.sh: |
    #!/bin/sh

    FILE=/root/.probe_last_height
    SYNCING=$(geth --datadir /root/.ethereum/base-mainnet attach --exec eth.syncing) || exit 1
    HEIGHT=$(geth --datadir /root/.ethereum/base-mainnet attach --exec eth.blockNumber) || exit 1

    # first time we are syncing from scratch
    if [ "$HEIGHT" = "0" ]; then
      exit 0
    fi

    if [ ! -f "$FILE" ]; then
      echo "$HEIGHT" >$FILE
      echo "Not getting new blocks"
      exit 1
    fi

    OLD=$(cat $FILE)
    echo "$HEIGHT" >$FILE
    if [ "$OLD" = "$HEIGHT" ]; then
      echo "Not getting new blocks"
      exit 1
    fi
    exit 0
