apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  ports:
    - port: 8545
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: 3500
      targetPort: beacon
      protocol: TCP
      name: beacon
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
