apiVersion: v1
kind: Service
metadata:
  name: {{ include "stellar-daemon.fullname" . }}-core
  labels:
    {{- include "stellar-daemon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 11625
      targetPort: peer
      protocol: TCP
      name: peer
    - port: 11626
      targetPort: http
      protocol: TCP 
      name: http
  selector:
    {{- include "stellar-daemon.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stellar-daemon.fullname" . }}-horizon
  labels:
    {{- include "stellar-daemon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "stellar-daemon.selectorLabels" . | nindent 4 }}
