apiVersion: v1
kind: Service
metadata:
  name: {{ include "stellar-daemon.fullname" . }}
  labels:
    {{- include "stellar-daemon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: api
    - port: 11625
      targetPort: peer
      protocol: TCP
      name: peer
  selector:
    {{- include "stellar-daemon.selectorLabels" . | nindent 4 }}
