---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mirror-backups
spec:
  {{- if .Values.persistence.storageClass }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  volumeMode: Filesystem
  volumeBindingMode: Immediate
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
